### ISSUE TITLE
Need to reset github PR status to pending when re-running tests

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/APSIM.PerformanceTests#23]
After issuing a command to Jenkins to re-run the tests, Jenkins' status is set to pending but the performance tests' status is left as-is. Unsure if it would be better to do this from the jenkins end or the APSIM.Builds end but either way this should be fixed.

![image](https://user-images.githubusercontent.com/36427516/67443173-1a8bef00-f647-11e9-8c72-c70909833dba.png)

**Comment by ric394** [comment]
I believe the two checks that now show will change to pending if a 'retest this please jenkins' comment is made. I'll close this one off.
